// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"TMServerRTP","status":false,"description":"ひとつ上の階層にある audio, img を参照することで、複数の\r\nプロジェクトで画像、音声ファイルを共用します。","parameters":{"defaultLoadSystem":"0"}},
{"name":"TMCard","status":true,"description":"デッキ構成で勝敗が決まるタイプのカードゲームが\r\n遊べるようになります。","parameters":{"vnResult":"1","vnMaxDeck":"2","vnMaxCard":"3","vnMaxCost":"4","fixCardNum":"0","sameCard":"0","useItemCard":"1","useAutoText":"1","commandDeckEdit":"デッキ編集","statusWindowWidth":"360","maxAtk":"50","maxTurn":"50","animationDamage":"1","animationTypeBonus":"52","paramNames":"名前 レア度 コスト HP 攻撃力 タイプ スキル 固有スキル 継承スキル 属性","itemCardParamNames":"ため時間 基本効果 特殊効果","typeIcons":"76 78 81 79 176","typeSpeed":"1 4 0 2","elementIcons":"64 65 66 67 68 69 70 71","rareNames":"Common Uncommon Rare Legend","costIcon":"0","costIconSpace":"0","positionNames":"1st 2nd 3rd 4th 5th","itemCardPositionName":"ITM","deckNames":"デッキA デッキB デッキC デッキD デッキE","playerCardPositions":"128,264 272,184 368,184 464,184 560,184","playerItemCardPosition":"272,344","enemyCardPositions":"688,264 544,344 448,344 352,344 256,344","enemyItemCardPosition":"544,184","numberPositions":"128,488 208,456 688,488 608,456"}},
{"name":"DTextPicture","status":true,"description":"動的文字列ピクチャ生成プラグイン","parameters":{}},
{"name":"Sq_ruulett","status":true,"description":"ルーレットを動作させるために必要です。\r\n詳しくはヘルプを見てください。","parameters":{}},
{"name":"SlotMachine","status":true,"description":"Slot Machine scene","parameters":{"Variable ID":"30","Help Text":"カーソルキーの上でベット、カーソルキーの下でスタート","Won Text":"おめでとうございます！Win Coin枚獲得です！","Lost Text":"残念でした。","Replay Text":"もう一度やりますか？","Coin Full Text":"コイン枚数が制限に達しました。","Bet Text":"ベット","Spin Text":"スピン","Yes Text":"はい","No Text":"いいえ"}},
{"name":"TMMoveEx","status":true,"description":"壁衝突音やリージョンによる通行設定などの機能を追加します。","parameters":{"passableRegionId":"251","dontPassRegionId":"252","seKnockWall":"<name:Blow1><volume:40><pitch:100>","knockWallPan":"75","knockWallInterval":"90","turnKeyCode":"83","movableRegion1":"","movableRegion2":"","movableRegion3":"","movableRegion4":"","movableRegion5":"","movableRegion6":"","movableRegion7":"","movableRegion8":"","movableRegion9":"","movableRegion10":""}},
{"name":"LotteryBox","status":true,"description":"ランダムでアイテムや装備、お金が手に入る抽選箱を提供します。","parameters":{"Result Variable Number":"5","Name Variable Number":"6","Auto Empty Mode":"ON"}},
{"name":"DebtRepayment","status":true,"description":"所持金マイナスプラグイン","parameters":{}},
{"name":"TMTyping","status":true,"description":"ミニタイピングゲームが遊べるコマンドを追加します。","parameters":{"typingCommand":"[タイピング]","typingColor":"2","typingSe":"Switch1","typingSeVolume":"90","typingSePitch":"130","typingSePan":"0"}},
{"name":"PD_DelayTitle","status":true,"description":"タイトル画面の各画像の表示にディレイとフェードイン機能を追加します。","parameters":{"Delay BG1":"0","Fade BG1":"60","Delay BG2":"60","Fade BG2":"60","Delay Title":"120","Fade Title":"60","Delay Command":"180","Pass To Decide":"1"}},
{"name":"SwitchOnLoad","status":true,"description":"ゲームをロードしたときに指定のスイッチをONにします。","parameters":{"Switch ID":"30"}},
{"name":"OuterSelfSwitch","status":true,"description":"他のイベントのセルフスイッチを操作します。","parameters":{}},
{"name":"Gacha","status":true,"description":"ランダムにアイテムを取得します。","parameters":{"Help Message Text":"1回Required Amount\\Zenyでラグガチャを引きます","Button Text":"ラグガチャを引く","Get Message Text":"GET Item Nameカード","Show Item Description":"1","Effect":"119","Rank1 Effect":"-1","Rank2 Effect":"-1","Rank3 Effect":"-1","Rank4 Effect":"-1","Rank5 Effect":"-1","ME":"勝利ファンファーレ","Required Amount":"5000"}},
{"name":"SceneSoundTest","status":true,"description":"サウンドテストプラグイン","parameters":{"コマンド名称":"サウンドテスト","タイトルに追加":"OFF","メニューに追加":"OFF","音量名称":"音量","ピッチ名称":"ピッチ","位相名称":"位相","背景ピクチャ":"","読込形式":"CSV","管理番号":""}},
{"name":"BatchProcessManager","status":true,"description":"バッチ処理プラグイン","parameters":{}}
];
